Mubeen@DESKTOP-2VSO8HL MINGW64 /l/Users/Mubeen/AndroidStudioProjects/Naiki (master) $ git init Reinitialized existing Git repository in L:/Users/Mubeen/AndroidStudioProjects/Naiki/.git/
Mubeen@DESKTOP-2VSO8HL MINGW64 /l/Users/Mubeen/AndroidStudioProjects/Naiki (master)
$ git status
On branch master
Your branch is up to date with 'origin/master'.

Untracked files:
  (use "git add <file>..." to include in what will be committed)
        .idea/vcs.xml

nothing added to commit but untracked files present (use "git add" to track)

Mubeen@DESKTOP-2VSO8HL MINGW64 /l/Users/Mubeen/AndroidStudioProjects/Naiki (master)
$ git add -a
error: unknown switch `a'
usage: git add [<options>] [--] <pathspec>...

    -n, --dry-run         dry run
    -v, --verbose         be verbose

    -i, --interactive     interactive picking
    -p, --patch           select hunks interactively
    -e, --edit            edit current diff and apply
    -f, --force           allow adding otherwise ignored files
    -u, --update          update tracked files
    --renormalize         renormalize EOL of tracked files (implies -u)
    -N, --intent-to-add   record only the fact that the path will be added later
    -A, --all             add changes from all tracked and untracked files
    --ignore-removal      ignore paths removed in the working tree (same as --no-all)
    --refresh             don't add, only refresh the index
    --ignore-errors       just skip files which cannot be added because of errors
    --ignore-missing      check if - even missing - files are ignored in dry run
    --chmod (+|-)x        override the executable bit of the listed files
    --pathspec-from-file <file>
                          read pathspec from file
    --pathspec-file-nul   with --pathspec-from-file, pathspec elements are separated with NUL character

Mubeen@DESKTOP-2VSO8HL MINGW64 /l/Users/Mubeen/AndroidStudioProjects/Naiki (master)
$ git status
On branch master
Your branch is up to date with 'origin/master'.

Untracked files:
  (use "git add <file>..." to include in what will be committed)
        .idea/vcs.xml

nothing added to commit but untracked files present (use "git add" to track)

Mubeen@DESKTOP-2VSO8HL MINGW64 /l/Users/Mubeen/AndroidStudioProjects/Naiki (master)
$ cd Naiki
bash: cd: Naiki: No such file or directory

Mubeen@DESKTOP-2VSO8HL MINGW64 /l/Users/Mubeen/AndroidStudioProjects/Naiki (master)
$

Mubeen@DESKTOP-2VSO8HL MINGW64 /l/Users/Mubeen/AndroidStudioProjects/Naiki (master)
$ git push origin master

fatal: unable to access 'https://github.com/mr-mubeen/Naiki-DonationApp.git/': Could not resolve host: github.com

Mubeen@DESKTOP-2VSO8HL MINGW64 /l/Users/Mubeen/AndroidStudioProjects/Naiki (master)
$

Mubeen@DESKTOP-2VSO8HL MINGW64 /l/Users/Mubeen/AndroidStudioProjects/Naiki (master)updated
git init